name: go test linux

on: [push]

permissions:
  contents: read

jobs:
  go-test-linux:
    name: "go test with OS: ${{ matrix.os }}; Go: ${{ matrix.go }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: ["1.21"]
        os: [ubuntu-latest]

    services:
      servegrpc:
        env:
          SENZING_TOOLS_DATABASE_URL: sqlite3://na:na@/tmp/sqlite/G2C.db
          SENZING_TOOLS_ENABLE_ALL: true
        image: senzing/serve-grpc
        ports:
          - 8261:8261

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: run go test
        run: go test -v -p 1 ./...
