name: go test darwin

on: [push]

permissions:
  contents: read

jobs:
  go-test-darwin:
    name: "go test with OS: ${{ matrix.os }}; Go: ${{ matrix.go }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: ["1.21"]
        os: [macos-latest]

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: install Docker
        uses: docker-practice/actions-setup-docker@v1
        timeout-minutes: 12

      - name: gRPC service
        run: docker run --detach --env SENZING_TOOLS_COMMAND=serve-grpc --env SENZING_TOOLS_DATABASE_URL=sqlite3://na:na@/tmp/sqlite/G2C.db --env SENZING_TOOLS_ENABLE_ALL=true --publish 8261:8261 senzing/senzing-tools:latest

      - run: go test -v -p 1 ./...
