# Based on
# - https://github.com/marketplace/actions/setup-go-environment

name: go-test-darwin.yaml

on: [push]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        go: ["1.20"]
    name: Go ${{ matrix.go }} - darwin
    services:
      servegrpc:
        env:
          SENZING_TOOLS_ENABLE_ALL: true
        image: senzing/serve-grpc
        ports:
          - 8261:8261
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      # - run: go test -v -p 1 ./...
      - run: go test -v ./.
      - run: go test -v ./g2config
      - run: go test -v ./g2configmgr
      - run: go test -v ./g2diagnostic
      # - run: go test -v ./g2engine
      - run: go test -v ./g2product
      - run: go test -v ./helper
